const EmitterEvents = {

    MODIFY_PHONE_SUCCESS: 'MODIFY_PHONE_SUCCESS',

    ADD_DEVICE_SUCCESS: 'ADD_DEVICE_SUCCESS',

    ADD_STATION_SUCCESS: 'ADD_STATION_SUCCESS',

    INVALID_TOKEN_TO_LOGIN: 'INVALID_TOKEN_TO_LOGIN',

    ANDROID_BACK_HARDWARE: 'hardwareBackPress',

    CONNECTION_CHANGE: 'connectionChange',

    NETWORK_CONNECTION: 'NETWORK_CONNECTION',

    HIDE_MODAL: 'HIDE_MODAL',

    RECEIVED_NOTIFICATION: 'RECEIVED_NOTIFICATION',

    MULTI_LANGUAGE: 'MULTI_LANGUAGE',
};

export default EmitterEvents;
